version: '3.3'
services:
    enverproxy-mqtt:
        container_name: enverproxy-mqtt
        restart: unless-stopped
        build: .
        ports:
            - '1898:1898'
            - '10013:1898'
            - '14889:1898'
        environment:
            - LISTEN_PORT=1898
            - VERBOSITY=3
        volumes:
            - './enverproxy-mqtt.conf:/data/app/enverproxy-mqtt.conf:ro'
            - '/etc/localtime:/etc/localtime:ro'
        healthcheck:
            test: ["CMD-SHELL", "netstat -ltn | grep -c 1898 || exit 1"]
